### ISSUE TITLE
Quill Syntax highlight module 커스텀하기

### ISSUE THREAD

**Issue by Ryan-TheLion** [Ryan-TheLion/blog-editor-frontend#5]
Quill에서 제공하는 syntax highlight module의 기능을 하는 embed block blot을 생성해서 custom하고자 한다.

## tasks
- [ ] 기본 동작 확인
  - [ ] custom-code-syntax blot 생성 및 module에 등록
  - [ ] custom-code-syntax blot(format) icon을 custom toolbar에 추가
- [ ] 잘 작동할 경우 component로 custom해서 사용할 수 있는지 확인하고, copy 기능을 추가하기 위해 추가 작업 (작업 시간 소요 및 변동 가능)

## reference
[https://6unu.net/post/public-1621060406818](https://6unu.net/post/public-1621060406818)
